config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'contacts#index'
  resources :contacts, :custom_fields
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: true, email: true
  serialize :contact_fields, Hash

  belongs_to :user

  # Given a key (e.g: :age)
  # remove it from contact_fields
  # attribute of a contact.
  #
  # These method is used
  # when some custom field is removed
  # and some contact makes use of this field
  #
  def remove_custom_field(key)
    self.contact_fields.delete(key)
  end

end

app/models/custom_field.rb
class CustomField < ActiveRecord::Base

  FIELDS = %w[text_field text_area combo_box]

  before_save { |field| field.name = field.name.downcase }

  validates :name, :field_type, presence: true

  belongs_to :user

  def select_options
    return if self.field_type != "combo_box"
    self.combo_options.split(',').map(&:strip)
  end

  # When a CustomField is removed
  # we need also remove this field 
  # of contacts that use it
  #
  def remove
   contacts_that_use_this_field = 
     Contact.all.select {
     |contact| contact.contact_fields.include? self.name.downcase.to_sym
   }
   
   contacts_that_use_this_field.each do |contact|
     contact.remove_custom_field(self.name.downcase.to_sym)
     contact.save!
   end

   self.destroy
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts
  has_many :custom_fields
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      "login"
    else
      "application"
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = current_user.contacts
  end

  def new
    @contact       = Contact.new
    set_custom_fields
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
      else
        set_custom_fields
        format.html { render :new }
      end
    end
  end

  def edit
    set_custom_fields
  end

  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
      else
        set_custom_fields
        format.html { render :edit }
      end
    end
  end

  def show
    set_custom_fields
  end

  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :user_id).tap do |whitelist|
      whitelist[:contact_fields] = params[:contact][:contact_fields]
    end
  end

 def set_contact
   @contact = current_user.contacts.find(params[:id])
 end

 def set_custom_fields
   @custom_fields =  current_user.custom_fields
 end

end

app/controllers/custom_fields_controller.rb
class CustomFieldsController < ApplicationController

  before_action :set_custom_field, only: [:destroy]

  def index
    @fields = current_user.custom_fields
  end

  def new
    @custom_field = CustomField.new
  end

  def create
    @custom_field         = CustomField.new(custom_field_params)
    @custom_field.user_id = current_user.id

    respond_to do |format|
      if @custom_field.save
        format.html { redirect_to :custom_fields, notice: 'Custom Field was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @custom_field.remove

    respond_to do |format|
      format.html { redirect_to custom_fields_url, notice: 'Custom Field was successfully destroyed.' }
    end
  end

  private
  def custom_field_params
    params.require(:custom_field).permit(:name, :field_type, :combo_options, :user_id)
  end

 def set_custom_field
   @custom_field = current_user.custom_fields.find(params[:id])
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def field_content(contact, field)
    value = contact.contact_fields[field.name.downcase.to_sym]
    value.blank? ? '-' : value
  end
end

app/views/contacts/_form.html.erb
<div class="ui form">
    <%= form_for(@contact) do |f| %>
        
        <%= render partial: "shared/validations", locals: {record: @contact} %>

        <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
        </div>

        <div class="field">
            <%= f.label :email %><br>
            <%= f.text_field :email %>
        </div>

        <%= f.fields_for :contact_fields, OpenStruct.new(@contact.contact_fields) do |builder| %>
            <% @custom_fields.each do |field| %>
                <%= render "contacts/fields/#{field.field_type}", field: field, f: builder  %>
            <% end  %>
        <% end %>
        
        <%= f.submit class: "ui primary button" %> 
        <%= link_to "Back", :root, class: "ui button" %>
    <%end %>
</div>

app/views/contacts/fields/_combo_box.html.erb
<div class="field">
	<%= f.label field.name %></br>
	<%= f.select(field.name, field.select_options, {}, {class: "ui fluid dropdown"}) %>	
</div>

app/views/contacts/fields/_text_area.html.erb
<div class="field">
  <%= f.label field.name %></br>
  <%= f.text_area field.name %>
</div>

app/views/contacts/fields/_text_field.html.erb
<div class="field">
  <%= f.label field.name %></br>
  <%= f.text_field field.name %>
</div>

app/views/contacts/index.html.erb
<h1>My Contacts</h1>

<% if @contacts.empty?  %>
    <div class="ui info message">
        <div class="header">
            Do you don't have any contacts yet
        </div>
        <ul class="list">
            <li>Create a new one clicking in 'New Contact'</li>
            <li>Create a new custom field for your contact form clicking in 'Custom Fields'</li>
        </ul>
    </div>
<% else  %>
    <table class="ui table">
        <thead>
            <tr>
                <td>Name</td>
                <td>E-mail</td>
                <td>Options</td>
            </tr>
        </thead>
        <tbody>
            <% @contacts.each do |contact| %>
                <tr>
                    <td><%= link_to contact.name, contact %></td>
                    <td><%= link_to contact.email, contact %></td>
                    <td><%= link_to "Edit", edit_contact_path(contact) %> or <%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
            <% end  %>
        </tbody>
    </table>
<% end %>
<br/>

<%= link_to 'New Contact', new_contact_path, class: "primary ui button" %> or
<%= link_to 'Custom Fields', custom_fields_path, class: "primary ui button"  %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

app/views/contacts/show.html.erb
<h1 class="ui header"><%= @contact.email %></h1>

<b><label>Name:</label></b> <%= @contact.name %><br/>
<b><label>Email:</label></b> <%= @contact.email %><br/>

<% @custom_fields.all.each do |field|  %>
    <b><label><%= field.name %>:<label></b> <%= field_content(@contact, field)  %><br/>
<% end  %>

<br/>
<%= link_to "Back", :contacts, class: "ui button" %>

app/views/custom_fields/_form.html.erb
<div class="ui form">
    <%= form_for @custom_field do |f| %>

        <%= render partial: "shared/validations", locals: {record: @custom_field} %>

        <div class="field">
            <%= f.label :name %> 
            <%= f.text_field :name%>
        </div><br/>

        <div class="field">
            <%= f.label :field_type %>
            <%= f.select(:field_type, CustomField::FIELDS, {}, {class: "ui fluid dropdown"}) %>

            <div class="combo-option" style="display: none"><br/>
                <div class="field">
                    <%= f.label :combo_options %>
                    <%= f.text_field :combo_options%>
                </div>
                <small>Use a comma to separate the options</small>
            </div>
        </div
        <br/><br/>

        <%= f.submit "Create Custom Field", class: "ui primary button " %>
        <%= link_to "Back", :custom_fields, class: "ui button" %>
        <%= link_to "Back to Contacts", :root, class: "ui button" %>
    <% end %>
</div>

app/views/custom_fields/edit.html.erb
<%= render 'form' %>

app/views/custom_fields/index.html.erb
<table class="ui table">
    <thead>
        <tr>
            <td>Name</td>
            <td>Type</td>
            <td>Other</td>
            <td>Options</td>
        </tr>
    </thead>
    <tbody>
        <% @fields.each do |field|%>
            <tr>
                <td><%= field.name %></td>
                <td><%= field.field_type %></td>
                <td><%= field.combo_options %></td>
                <td><%= link_to 'Destroy', field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>        
    </tbody>
</table>

<%= link_to "Add new Custom Field", new_custom_field_path, class: "primary ui button" %>
<%= link_to "Back to Contacts", :root, class: "ui button" %>

app/views/custom_fields/new.html.erb
<h1>New Custom Field</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>ContactsRd</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div class="main-content">
            <%= current_user.email %> - <%= link_to "Sign out", destroy_user_session_path, method: :delete %>


            <div class="row">
                <div class="small-3 small-centered columns"> <h3>RD Contacts</h3></div>
                <%= semantic_flash %>
                
                <%= yield %>
            </div>
        </div>
        </div>
    </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactsRd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="main-content">
        <div class="row">
            <div class="small-3 small-centered columns"> <h3>RD Contacts</h3></div>
            <%= semantic_flash %>
            
            <%= yield %>
        </div>
    </div>
</body>
</html>

app/views/shared/_validations.html.erb
<% if record.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(record.errors.count, "error") %> prohibited this contact from being saved:</h2>

        <ul>
            <% record.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>